### ISSUE TITLE
Can you publish a new version with Webpack 5 support to npm?

### ISSUE THREAD

**Issue by Markionium** [microsoft/webpack-bundle-compare#29]
Hi,

I'm looking to use this plugin with webpack 5. It seems [this commit](https://github.com/microsoft/webpack-bundle-compare/commit/cf943d45d70a80b94e87b83384c820d198c4d298) adds support for webpack 5 but [it's not available on npm](https://www.npmjs.com/package/@mixer/webpack-bundle-compare).

If you would be able to publish a new version that would be appreciated!

Thanks!

**Comment by connor4312** [comment]
Published!
